-- Review queue: operator decision tracking for leads in review/hold tiers,
-- and any record that needs human attention (stale re-verifies, quarantined
-- duplicates, low-confidence enrichment).
--
-- Why a separate column instead of overloading export_tier:
--   - export_tier is computed from composite_score + suppression/dedupe state
--     and is regenerated by the scoring engine on every re-scrub. It must
--     not carry operator intent.
--   - review_state is the operator-facing decision and survives re-scoring.
--     A lead can be 'approved' for export even if its tier is 'review'
--     (policy=manual) — that's the whole point of the review queue.

alter table public.leads
  add column if not exists review_state text
    check (review_state in ('pending','approved','rejected','quarantined','reverify')),
  add column if not exists review_decided_at  timestamptz,
  add column if not exists review_decided_by  uuid references auth.users(id),
  add column if not exists review_reason      text;

comment on column public.leads.review_state is
  'Operator decision for review-queue leads. NULL = not in queue. pending = needs operator. approved = ok to export despite manual policy. rejected = never export. quarantined = held pending investigation. reverify = re-run scrub before deciding.';

-- Fast lookup for the review queue UI: leads in review/hold tiers that
-- still need a decision.
create index if not exists idx_leads_review_pending
  on public.leads (client_id, review_state, composite_score desc)
  where review_state = 'pending';

-- Distinct index for the "needs reverify" job (cron picks these up first).
create index if not exists idx_leads_review_reverify
  on public.leads (client_id, review_state)
  where review_state = 'reverify';

-- =========================================================
-- Backfill: mark existing review/hold tier leads as pending so the queue
-- isn't empty on first load. Discard tier intentionally stays NULL —
-- those records are terminal and don't belong in an operator queue.
-- =========================================================
update public.leads
set review_state = 'pending',
    review_reason = case
      when is_suppressed then 'auto: suppressed'
      when is_duplicate  then 'auto: duplicate'
      when export_tier = 'review' then 'auto: composite below auto-export threshold'
      when export_tier = 'hold'   then 'auto: composite below review threshold'
      else 'auto: needs review'
    end
where review_state is null
  and is_scrubbed = true
  and export_tier in ('review','hold');

-- =========================================================
-- Extend the quality rollup with review-queue counts.
-- security_invoker stays inherited from 0006 since CREATE OR REPLACE keeps
-- view options unless explicitly changed.
-- =========================================================
create or replace view public.v_client_quality as
select
  c.id                                                        as client_id,
  count(l.id) filter (where l.is_scrubbed)                    as scrubbed_total,
  count(l.id) filter (where l.export_tier = 'premium')        as tier_premium,
  count(l.id) filter (where l.export_tier = 'standard')       as tier_standard,
  count(l.id) filter (where l.export_tier = 'prospecting')    as tier_prospecting,
  count(l.id) filter (where l.export_tier = 'review')         as tier_review,
  count(l.id) filter (where l.export_tier = 'hold')           as tier_hold,
  count(l.id) filter (where l.export_tier = 'discard')        as tier_discard,
  count(l.id) filter (where l.review_state = 'pending')       as review_pending,
  count(l.id) filter (where l.review_state = 'approved')      as review_approved,
  count(l.id) filter (where l.review_state = 'rejected')      as review_rejected,
  count(l.id) filter (where l.review_state = 'reverify')      as review_reverify,
  avg(l.composite_score)  filter (where l.is_scrubbed)        as avg_composite,
  count(l.id) filter (
    where l.is_scrubbed
      and (l.verified_at is null or l.verified_at < now() - interval '90 days')
  ) as stale_count
from public.clients c
left join public.leads l on l.client_id = c.id
group by c.id;

alter view public.v_client_quality set (security_invoker = true);
